nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/api/': ~